CREATE TABLE users(
  FIRST_NAME TEXT NOT NULL,
  LAST_NAME TEXT NOT NULL,
  AGE INTEGER NOT NULL,
  COUNTRY TEXT NOT NULL,
  PHONE TEXT NOT NULL,
  BALANCE INTEGET NOT NULL
);


SELECT first_name, age
FROM users 
ORDER BY first_name asc, age desc;